[build]
  publish = "public"
  command = "composer install && npm run prod"

[context.production.environment]
  PHP_VERSION = "8.2"

[context.deploy-preview.environment]
  PHP_VERSION = "8.2"

[context.branch-deploy.environment]
  PHP_VERSION = "8.2"
